#!/data/data/com.termux/files/usr/bin/bash
pkg install wget openssl-tool proot -y && hash -r && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Kali/kali.sh && chmod +x * &&bash kali.sh
./start-kali.sh
